title: Siriluk Kanchanakungwankul   
#logo: /assets/img/headshort_circle.png
description: Data Science | Machine Learning | Ph.D. in Computational Chemistry
show_download: True
theme: jekyll-theme-minimal
